# Generated by Django 4.2.11 on 2024-12-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Pay', 'Pay'), ('Receive', 'Receive')], max_length=100),
        ),
    ]
